version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: heloc-postgres
    environment:
      POSTGRES_DB: heloc_accelerator
      POSTGRES_USER: heloc_user
      POSTGRES_PASSWORD: heloc_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/02-init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U heloc_user -d heloc_accelerator"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: heloc-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@helocaccel.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:

networks:
  default:
    name: heloc-network
